import type { MarketSearchRow } from './query-compiler';

const base: Omit<MarketSearchRow, 'id' | 'playerName' | 'playerAliases' | 'position' | 'year' | 'cardNumber' | 'rookie' | 'parallel' | 'raw' | 'gradingCompanyKey' | 'grade' | 'certificationNumber' | 'sourceKey' | 'saleType' | 'marketStatus' | 'saleAt' | 'allInMinor' | 'bidCount' | 'dealScore' | 'sellTimingScore' | 'confidence' | 'liquidity' | 'priceTrend' | 'purchaseStatus' | 'owned' | 'watched' | 'profitMinor' | 'roiBps' | 'outcomeStatus'> = {
  isDemo: true,
  teamShown: 'Washington',
  currentTeam: 'Washington',
  conference: 'NFC',
  division: 'NFC East',
  era: '2020s',
  manufacturer: 'Panini',
  brand: 'Prizm',
  setName: 'Prizm',
  subset: null,
  playerStatus: 'ACTIVE',
  serialDenominator: null,
  autograph: false,
  autographType: 'NONE',
  memorabilia: false,
  memorabiliaType: 'NONE',
  qualifier: null,
  population: 500,
  currency: 'USD',
  daysOnMarket: 5,
  matchScore: 0.98,
  inclusionStatus: 'INCLUDED',
  exclusionCodes: [],
  holdingDays: 0,
};

export const demoMarketRows: readonly MarketSearchRow[] = Object.freeze([
  {
    ...base,
    id: 'DEMO-SCAN-001', playerName: 'Patrick Mahomes II', playerAliases: ['Pat Mahomes', 'Showtime'],
    teamShown: 'Kansas City Chiefs', currentTeam: 'Kansas City Chiefs', conference: 'AFC', division: 'AFC West',
    position: 'QB', year: 2020, cardNumber: '2', rookie: false, parallel: 'Silver', raw: false,
    gradingCompanyKey: 'psa', grade: 10, certificationNumber: 'DEMO-PSA-001', sourceKey: 'DEMO / PLACEHOLDER — eBay manual',
    saleType: 'AUCTION', marketStatus: 'ACTIVE', saleAt: '2026-08-10T12:00:00Z', allInMinor: 80_000n, bidCount: 14,
    dealScore: 5, sellTimingScore: -2, confidence: 82, liquidity: 76, priceTrend: 'RISING', purchaseStatus: 'PURCHASED',
    owned: true, watched: true, profitMinor: 12_500n, roiBps: 1_850, outcomeStatus: 'MATURED',
  },
  {
    ...base,
    id: 'DEMO-SCAN-002', playerName: 'Demo Receiver', playerAliases: ['D. Receiver'], position: 'WR', year: 2022,
    cardNumber: '188', rookie: false, parallel: 'Blue', raw: false, gradingCompanyKey: 'psa', grade: 9,
    certificationNumber: 'DEMO-PSA-002', sourceKey: 'DEMO / PLACEHOLDER — COMC manual', saleType: 'FIXED_PRICE',
    marketStatus: 'ACTIVE', saleAt: '2026-08-09T12:00:00Z', allInMinor: 25_000n, bidCount: 0, dealScore: -3,
    sellTimingScore: 4, confidence: 65, liquidity: 54, priceTrend: 'FLAT', purchaseStatus: 'PASSED', owned: false,
    watched: true, profitMinor: null, roiBps: null, outcomeStatus: 'MATURED',
  },
  {
    ...base,
    id: 'DEMO-SCAN-003', playerName: 'Demo Rookie Quarterback', playerAliases: ['Demo QB'], position: 'QB', year: 2024,
    cardNumber: '301', rookie: true, parallel: 'Base', raw: false, gradingCompanyKey: 'sgc', grade: 10,
    certificationNumber: 'DEMO-SGC-003', sourceKey: 'DEMO / PLACEHOLDER — auction CSV', saleType: 'AUCTION',
    marketStatus: 'ACTIVE', saleAt: '2026-08-08T12:00:00Z', allInMinor: 43_500n, bidCount: 8, dealScore: 7,
    sellTimingScore: -5, confidence: 58, liquidity: 62, priceTrend: 'RISING', purchaseStatus: 'MISSED', owned: false,
    watched: true, profitMinor: null, roiBps: null, outcomeStatus: 'PENDING',
  },
  {
    ...base,
    id: 'DEMO-SCAN-004', playerName: 'Demo Hall of Fame Back', playerAliases: ['Demo HOF RB'], position: 'RB', year: 1998,
    era: '1990s', playerStatus: 'RETIRED', cardNumber: '44', rookie: false, parallel: null, raw: false,
    gradingCompanyKey: 'bgs', grade: 9.5, certificationNumber: 'DEMO-BGS-004', sourceKey: 'DEMO / PLACEHOLDER — local deal',
    saleType: 'LOCAL', marketStatus: 'LOCAL_OFFER', saleAt: '2026-08-07T12:00:00Z', allInMinor: 12_000n, bidCount: null,
    dealScore: 1, sellTimingScore: 0, confidence: 41, liquidity: 28, priceTrend: 'FALLING', purchaseStatus: 'CANCELLED',
    owned: false, watched: false, profitMinor: null, roiBps: null, outcomeStatus: 'INVALIDATED',
  },
  {
    ...base,
    id: 'DEMO-SCAN-005', playerName: 'Demo Tight End', playerAliases: [], position: 'TE', year: 2023, cardNumber: '77',
    rookie: true, parallel: 'Green', raw: true, gradingCompanyKey: null, grade: null, certificationNumber: null,
    sourceKey: 'DEMO / PLACEHOLDER — card show', saleType: 'LOCAL', marketStatus: 'LOCAL_OFFER',
    saleAt: '2026-08-06T12:00:00Z', allInMinor: 4_000n, bidCount: null, dealScore: 0, sellTimingScore: 0,
    confidence: 32, liquidity: 19, priceTrend: 'UNKNOWN', purchaseStatus: 'UNDECIDED', owned: false, watched: false,
    profitMinor: null, roiBps: null, outcomeStatus: 'PENDING',
  },
  {
    ...base,
    id: 'DEMO-SCAN-006', playerName: 'Demo Kicker', playerAliases: [], position: 'K', year: 2021, cardNumber: '211',
    rookie: false, parallel: 'Gold /10', serialDenominator: 10, raw: false, gradingCompanyKey: 'psa', grade: 9,
    certificationNumber: 'DEMO-PSA-006', sourceKey: 'DEMO / PLACEHOLDER — private sale', saleType: 'FIXED_PRICE',
    marketStatus: 'SOLD', saleAt: '2026-08-05T12:00:00Z', allInMinor: 9_500n, bidCount: null, dealScore: 4,
    sellTimingScore: 3, confidence: 48, liquidity: 22, priceTrend: 'FLAT', purchaseStatus: 'PURCHASED', owned: true,
    watched: false, profitMinor: 2_100n, roiBps: 2_211, outcomeStatus: 'MATURED',
  },
]);